"""First Revision

Revision ID: ce51c29ce5a7
Revises: f520dd246110
Create Date: 2024-01-09 10:48:27.723066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce51c29ce5a7'
down_revision = 'f520dd246110'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
